[project]
name = "dataviz"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bleach>=6.3.0",
    # Stick to LTS for easier upgrades
    "django==5.2.*",
    "django-ckeditor-5>=0.2.20",
    "django-countries>=8.2.0",
    "django-enumfields>=2.1.1",
    "django-environ>=0.13.0",
    "django-haystack>=3.3.0",
    "djangorestframework>=3.17.1",
    # Haystack doesn't support ES8 yet, upstream issue:
    # https://github.com/django-haystack/django-haystack/issues/1980
    "elasticsearch==7.*",
    "gunicorn>=26.0.0",
    "jinja2>=3.1.6",
    "lxml>=6.1.1",
    "pyexcel>=0.7.4",
    "pyexcel-io>=0.6.7",
    "pyexcel-xls>=0.7.1",
    "pyexcel-xlsx>=0.6.1",
    "pymssql>=2.3.13",
    "pytz>=2026.2",
    "requests>=2.34.2",
    "sentry-sdk>=2.60.0",
    "wait-for-it>=2.3.0",
]

[dependency-groups]
dev = [
    "coverage>=7.14.0",
    "django-debug-toolbar>=6.3.0",
    "django-extensions>=4.1",
    "factory-boy>=3.3.3",
    "ipdb>=0.13.13",
    "ipython>=9.13.0",
    "ipython-autotime>=0.3.2",
    "pytest>=9.0.3",
    "pytest-cov>=7.1.0",
    "pytest-django>=4.12.0",
    "pytest-subtests>=0.15.0",
    "ruff>=0.15.14",
]

[tool.uv]
exclude-newer = "14 days"

[tool.ruff.lint]
select = [
    "E4", # pycodestyle
    "E7",
    "E9",
    "F", # pyflakes
    "I", # isort
    "N", # pep8-naming
    "S", # flake8-bandit
    "FBT", # flake8-boolean-trap
    "B", # flake8-bugbear
    "C4", # flake8-comprehensions
    "DTZ", # flake8-datetimez
    "T10", # flake8-debugger
    "DJ", # flake8-django
    "LOG", # flake8-logging
    "G", # flake8-logging-format
    "T20", # flake8-print
    "RSE", # flake8-raise
    "RET", # flake8-return
    "SIM", # flake8-simplify
    "INT", # flake8-gettext
    # "PTH", # flake8-use-pathlib
    "NPY", # numpy rules
]
ignore = [
    # Allow boolean default positional arguments, as django has many of those.
    "FBT001",
    "FBT002",
    "FBT003",
    # Allow using "assert"
    "S101",
    # Allow using mark_safe
    "S308",
    # Allow NULL values for text fields, not the best practice but a pain to migrate
    "DJ001",
]
