# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 21:34
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import dv.lib.models
import dv.models
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_allocation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_allocation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('order', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=(dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FinancialMechanism',
            fields=[
                ('code', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('grant_name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('code', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
            bases=(dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.URLField(max_length=2000)),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('summary', models.TextField(null=True)),
                ('image', models.URLField(max_length=2000)),
                ('is_partnership', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='NUTS',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
                'ordering': ['code'],
            },
            bases=(dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', enumfields.fields.EnumField(enum=dv.models.Organisation.ORGANISATION_TYPE, max_length=9)),
                ('country', models.CharField(max_length=64)),
                ('city', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('domestic_name', models.CharField(max_length=256, null=True)),
                ('geotarget', models.CharField(max_length=256)),
                ('nuts', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
            bases=(dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Organisation_OrganisationRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_programme', models.NullBooleanField(default=None)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='dv.Organisation')),
            ],
            options={
                'abstract': False,
            },
            bases=(dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganisationRole',
            fields=[
                ('code', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
            bases=(dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OrganisationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', enumfields.fields.EnumField(enum=dv.models.OrganisationType.CATEGORY, max_length=26)),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('code', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('fixed_budget_line', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
            bases=(dv.models._FussyOutcomeCode, dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PrioritySector',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
            bases=(dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('status', enumfields.fields.EnumField(enum=dv.models.Programme.STATUS, max_length=14)),
                ('url', models.CharField(max_length=256, null=True)),
                ('summary', models.TextField()),
                ('allocation_eea', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocation_norway', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_tap', models.BooleanField()),
                ('co_financing', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
            options={
                'abstract': False,
            },
            bases=(dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Programme_ProgrammeArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.Programme')),
            ],
            options={
                'abstract': False,
            },
            bases=(dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProgrammeArea',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('short_name', models.CharField(max_length=32)),
                ('order', models.SmallIntegerField()),
                ('objective', models.TextField()),
                ('is_not_ta', models.BooleanField()),
                ('url', models.CharField(max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProgrammeIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_text', models.CharField(default='', max_length=300)),
                ('achievement', models.IntegerField()),
                ('order', models.SmallIntegerField()),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.Indicator')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.Outcome')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.Programme')),
                ('programme_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.ProgrammeArea')),
            ],
            options={
                'abstract': False,
            },
            bases=(dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProgrammeOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocation', models.FloatField()),
                ('co_financing', models.FloatField()),
                ('result_text', models.CharField(default='', max_length=300)),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programmes', to='dv.Outcome')),
                ('programme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='dv.Programme')),
            ],
            bases=(dv.models._FussyOutcomeCode, dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('status', enumfields.fields.EnumField(enum=dv.models.Project.STATUS, max_length=11)),
                ('code', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=512)),
                ('nuts', models.CharField(max_length=5)),
                ('geotarget', models.CharField(max_length=256)),
                ('url', models.CharField(max_length=256, null=True)),
                ('allocation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('programme_co_financing', models.DecimalField(decimal_places=2, max_digits=15)),
                ('project_co_financing', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_eea', models.BooleanField()),
                ('is_norway', models.BooleanField()),
                ('has_ended', models.BooleanField()),
                ('is_dpp', models.BooleanField()),
                ('is_positive_fx', models.BooleanField()),
                ('is_improved_knowledge', models.BooleanField()),
                ('is_continued_coop', models.BooleanField()),
                ('is_published', models.BooleanField()),
                ('summary', models.TextField()),
                ('financial_mechanism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.FinancialMechanism')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.Outcome')),
                ('priority_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.PrioritySector')),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.Programme')),
                ('programme_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.ProgrammeArea')),
            ],
            options={
                'abstract': False,
            },
            bases=(dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='dv.Project')),
            ],
            options={
                'abstract': False,
            },
            bases=(dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('url', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=(dv.lib.models.ImportableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='StaticContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.State'),
        ),
        migrations.AddField(
            model_name='programmeoutcome',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.State'),
        ),
        migrations.AddField(
            model_name='programmeindicator',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dv.State'),
        ),
        migrations.AddField(
            model_name='programmearea',
            name='allocations',
            field=models.ManyToManyField(through='dv.Allocation', to='dv.State'),
        ),
        migrations.AddField(
            model_name='programmearea',
            name='financial_mechanism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.FinancialMechanism'),
        ),
        migrations.AddField(
            model_name='programmearea',
            name='priority_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.PrioritySector'),
        ),
        migrations.AddField(
            model_name='programme_programmearea',
            name='programme_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.ProgrammeArea'),
        ),
        migrations.AddField(
            model_name='programme',
            name='programme_areas',
            field=models.ManyToManyField(through='dv.Programme_ProgrammeArea', to='dv.ProgrammeArea'),
        ),
        migrations.AddField(
            model_name='programme',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.State'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='programme_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='dv.ProgrammeArea'),
        ),
        migrations.AddField(
            model_name='organisation_organisationrole',
            name='organisation_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='dv.OrganisationRole'),
        ),
        migrations.AddField(
            model_name='organisation_organisationrole',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_roles', to='dv.Programme'),
        ),
        migrations.AddField(
            model_name='organisation_organisationrole',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_roles', to='dv.Project'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='orgtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dv.OrganisationType'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='role',
            field=models.ManyToManyField(through='dv.Organisation_OrganisationRole', to='dv.OrganisationRole'),
        ),
        migrations.AddField(
            model_name='news',
            name='programmes',
            field=models.ManyToManyField(related_name='news', to='dv.Programme'),
        ),
        migrations.AddField(
            model_name='news',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='dv.Project'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='financial_mechanism',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.FinancialMechanism'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='programme_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.ProgrammeArea'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dv.State'),
        ),
        migrations.AlterUniqueTogether(
            name='programmeoutcome',
            unique_together=set([('programme', 'outcome', 'state')]),
        ),
        migrations.AlterUniqueTogether(
            name='programme_programmearea',
            unique_together=set([('programme', 'programme_area')]),
        ),
        migrations.AlterUniqueTogether(
            name='organisation_organisationrole',
            unique_together=set([('organisation', 'organisation_role', 'programme', 'project')]),
        ),
        migrations.AlterUniqueTogether(
            name='allocation',
            unique_together=set([('state', 'programme_area', 'financial_mechanism')]),
        ),
    ]
