# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 15:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='fixed_budget_line',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmeoutcome',
            name='state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dv.State'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outcome',
            name='code',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='programmeoutcome',
            unique_together=set([('programme', 'outcome', 'state')]),
        ),
    ]
