# Generated by Django 3.2.8 on 2021-10-12 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dv", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programme",
            name="url",
        ),
        migrations.RemoveField(
            model_name="project",
            name="url",
        ),
    ]
