# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nuts',
            options={'ordering': ['code']},
        ),
        migrations.AlterField(
            model_name='indicator',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
