# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0002_auto_20170208_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='programme',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dv.Programme'),
            preserve_default=False,
        ),
    ]
