# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0003_auto_20170222_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('link', models.URLField(max_length=2000)),
                ('created', models.DateTimeField(null=True)),
                ('updated', models.DateTimeField(null=True)),
                ('summary', models.TextField(null=True)),
                ('image', models.URLField(max_length=2000)),
                ('is_partnership', models.BooleanField(default=False)),
                ('programmes', models.ManyToManyField(to='dv.Programme')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dv.Project')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
