# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 18:22
from __future__ import unicode_literals

from django.db import migrations
import dv.models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0003_project_programme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='ptype',
            field=enumfields.fields.EnumField(enum=dv.models.Organisation.ORGANISATION_TYPE, max_length=9),
        ),
        migrations.AlterField(
            model_name='organisationrole',
            name='role',
            field=enumfields.fields.EnumField(enum=dv.models.OrganisationRole.ROLE, max_length=23),
        ),
        migrations.AlterField(
            model_name='organisationtype',
            name='category',
            field=enumfields.fields.EnumField(enum=dv.models.OrganisationType.CATEGORY, max_length=26),
        ),
        migrations.AlterField(
            model_name='prioritysector',
            name='type',
            field=enumfields.fields.EnumField(enum=dv.models.FINANCIAL_MECHANISM, max_length=6),
        ),
        migrations.AlterField(
            model_name='programme',
            name='status',
            field=enumfields.fields.EnumField(enum=dv.models.Programme.STATUS, max_length=14),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=enumfields.fields.EnumField(enum=dv.models.Project.STATUS, max_length=11),
        ),
    ]
