# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0003_importlog_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
