# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-17 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0003_auto_20170617_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmeindicator',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dv.State'),
        ),
    ]
