# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0004_auto_20171213_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actual_summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
