# Generated by Django 3.2.13 on 2022-06-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0004_update_achievement_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='thematic',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
