# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0004_auto_20170617_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='is_tap',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
