# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0005_programme_is_tap'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='programme_area',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='dv.ProgrammeArea'),
            preserve_default=False,
        ),
    ]
