# Generated by Django 3.2.5 on 2021-07-12 14:56

from django.db import migrations, models
import django.db.models.deletion
import dv.models
import enumfields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0005_project_actual_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='project',
            field=models.ForeignKey(db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news', to='dv.project'),
        ),
        migrations.AlterField(
            model_name='organisation_organisationrole',
            name='is_programme',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=enumfields.fields.EnumField(enum=dv.models.ProjectStatus, max_length=64),
        ),
    ]
