# Generated by Django 3.2.13 on 2022-09-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dv", "0005_project_thematic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="country",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="city",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="category",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="organisation",
            name="subcategory",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
