# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-22 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0006_project_programme_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='has_ended',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='is_continued_coop',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='is_dpp',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='is_improved_knowledge',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='is_positive_fx',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='is_published',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prioritysector',
            name='code',
            field=models.CharField(max_length=32, primary_key=True, serialize=False),
        ),
    ]
