# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-23 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0008_projecttheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttheme',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='dv.Project'),
        ),
    ]
