# Generated by Django 5.2.7 on 2025-11-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dv", "0009_alter_staticcontent_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="staticcontent",
            name="seo_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="staticcontent",
            name="seo_title",
            field=models.TextField(default=""),
        ),
    ]
