# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0009_auto_20170623_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmearea',
            name='is_not_ta',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programmearea',
            name='url',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
