# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0010_auto_20170628_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='programmeindicator',
            name='order',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
