# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-04 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0011_programmeindicator_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation_organisationrole',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_roles', to='dv.Programme'),
        ),
    ]
