# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-04 18:43
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0014_staticcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticcontent',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
