# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-13 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0015_auto_20170804_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation_organisationrole',
            name='is_implementing_partner',
            field=models.NullBooleanField(),
        ),
    ]
