# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-22 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0016_auto_20170813_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programmeoutcome',
            name='programme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='dv.Programme'),
        ),
    ]
