# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 11:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dv', '0018_auto_20170828_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organisation_organisationrole',
            name='is_implementing_partner',
        ),
        migrations.AddField(
            model_name='organisation',
            name='domestic_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
